### ISSUE TITLE
Parse piped expressions to Maxima's abs function

### ISSUE THREAD

**Issue by mattvague** [KQMATH/tex2max#28]
Would be really nice if tex2max supported parsing strings like ln|x| and transpiled them to ln(abs(x)). Seems doable, and I don't mind taking this on as I need it as soon as possible but if I could get some advice on where/how to start that'd be awesome. Thanks!

**Comment by andstor** [comment]
I have added some basic support for absolute value symbols in the branch **feat/abs**.

However, since we have based grouping of expressions on the distinction of opening "(" and closing parenthesis ")", braces and brackets, parsing "|" symbols is considerably more difficult.

Alternatively, one could make use of the "\left" and "\right" macros used in many LaTeX expression. However, they should only be used as a supplement, since LaTeX expressions are perfectly valid without them.

Please feel free to try to fix the problems marked with "[TODO](https://github.com/KQMATH/tex2max/blob/851ef5f7d4365ccac3ce3e03f441731a5b155fd6/src/post-parser.js#L194-L195)" in the post-parser.js file.

**Comment by mattvague** [comment]
@andstor Ah, awesome thank you! Yeah I imagined that was why it wasn't in master. I'll take a look and see how hard I think it would be.

One thing I was noticing is I didn't see any unit tests, was wondering if you thought that might be something worth adding to ease development and prevent regressions?

**Comment by andstor** [comment]
@mattvague Yes, we should definitely add unit testing. I have created an issue #29. Help would be much appreciated.
